name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm ci
      run: npm ci

    - name: deploy
      run: npm run deploy
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
